mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("r4_codes/", views.r4_codes, name="r4_codes"),
    path("r3_codes/", views.r3_codes, name="r3_codes"),
    path("r2_codes/", views.r2_codes, name="r2_codes"),
    path("r1_codes/", views.r1_codes, name="r1_codes"),
    path("r1_codes/<str:r_1_code>/", views.r1_codes_detail, name="r1_codes_detail"),
    path("r2_codes/<str:r_1_code>/<str:r_2_code>/", views.r2_codes_detail, name="r2_codes_detail"),
    path("r3_codes/<str:r_1_code>/<str:r_2_code>/<str:r_3_code>/", views.r3_codes_detail, name="r3_codes_detail"),
    path("r4_codes/<str:r_1_code>/<str:r_2_code>/<str:r_3_code>/<str:r_4_code>/", views.r4_codes_detail, name="r4_codes_detail"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
    
class R1Code(models.Model):
    r_1_code = models.CharField(primary_key=True, max_length=2, db_column='r_1_code')
    r_1_desc_en = models.CharField(max_length=50, db_column='r_1_desc_en', verbose_name="English Description")
    r_1_desc_tr = models.CharField(max_length=50, db_column='r_1_desc_tr', verbose_name="Turkish Description")

    def __str__(self):
        return self.r_1_code

    class Meta:
        managed = False
        db_table = 'r1_code'

class R2Code(models.Model):
    r_1_code = models.CharField(max_length=2, db_column='r_1_code', verbose_name="r1_Code")
    r_2_code = models.CharField(max_length=2, db_column='r_2_code', verbose_name="r2_Code")
    r_2_desc_en = models.CharField(max_length=150, db_column='r_2_desc_en', verbose_name="English Description")
    r_2_desc_tr = models.CharField(max_length=150, db_column='r_2_desc_tr', verbose_name="Turkish Description")
    code_r2 = models.CharField(primary_key=True, max_length=150, db_column='code_r2',editable= False)

    def __str__(self):
        return f"{self.r_1_code}-{self.r_2_code}"

    class Meta:
        managed = False
        db_table = 'r2_code'
        unique_together = ('r_1_code', 'r_2_code')

    def _do_insert(self, manager, using, fields, update_pk, raw):
        fields = [
            f for f in fields if f.attname not in ['code_r2']
        ]
        return super()._do_insert(manager, using, fields, update_pk, raw)
    
class R3Code(models.Model):
    r_1_code = models.CharField(max_length=2, db_column='r_1_code', verbose_name="r1_Code")
    r_2_code = models.CharField(max_length=2, db_column='r_2_code', verbose_name="r2_Code")
    r_3_code = models.CharField(max_length=2, db_column='r_3_code', verbose_name="r3_Code")
    r_3_desc_en = models.CharField(max_length=150, db_column='r_3_desc_en', verbose_name="English Description")
    r_3_desc_tr = models.CharField(max_length=150, db_column='r_3_desc_tr', verbose_name="Turkish Description")
    code_r3 = models.CharField(primary_key=True, max_length=8, db_column='code_r3',editable= False)

    def __str__(self):
        return f"{self.r_1_code}-{self.r_2_code}-{self.r_3_code}"

    class Meta:
        managed = False
        db_table = 'r3_code'
        unique_together = ('r_1_code', 'r_2_code', 'r_3_code')

    def _do_insert(self, manager, using, fields, update_pk, raw):
        fields = [
            f for f in fields if f.attname not in ['code_r3']
        ]
        return super()._do_insert(manager, using, fields, update_pk, raw)
    
    def _do_update(self, base_qs, using, pk_val, values, update_fields, forced_update):
        values = [
            value for value in values if value[0].attname not in ['code_r3']
        ]
        return super()._do_update(base_qs, using, pk_val, values, update_fields, forced_update)
    
class R4Code(models.Model):
    r_1_code = models.CharField(max_length=2, db_column='r_1_code', verbose_name="r1_Code")
    r_2_code = models.CharField(max_length=2, db_column='r_2_code', verbose_name="r2_Code")
    r_3_code = models.CharField(max_length=2, db_column='r_3_code', verbose_name="r3_Code")
    r_4_code = models.CharField(max_length=3, db_column='r_4_code', verbose_name="r4_Code")
    r_4_desc_en = models.CharField(max_length=160, db_column='r_4_desc_en', verbose_name="English Description")
    r_4_desc_tr = models.CharField(max_length=150, db_column='r_4_desc_tr', verbose_name="Turkish Description")
    w_ufe = models.DecimalField(max_digits=7, decimal_places=5)
    w_tufe = models.DecimalField(max_digits=7, decimal_places=5)
    w_inf_usd = models.DecimalField(max_digits=7, decimal_places=5)
    w_inf_eur = models.DecimalField(max_digits=7, decimal_places=5)
    w_metal = models.DecimalField(max_digits=7, decimal_places=5)
    w_petrol = models.DecimalField(max_digits=7, decimal_places=5)
    w_cement = models.DecimalField(max_digits=7, decimal_places=5)
    w_electricity = models.DecimalField(max_digits=7, decimal_places=5)
    currency = models.CharField(max_length=3)
    administration = models.CharField(max_length=50, blank=True, null=True)
    admin_id = models.CharField(max_length=50, blank=True, null=True)
    r_loss = models.DecimalField(max_digits=7, decimal_places=5, blank=True, null=True)
    key_r4_simple = models.CharField(max_length=15, blank=True, null=True,editable= False)
    code_r4 = models.CharField(primary_key=True, max_length=8, db_column='code_r4',editable= False)

    def __str__(self):
        return f"{self.r_1_code}-{self.r_2_code}-{self.r_3_code}-{self.r_4_code}"

    class Meta:
        managed = False
        db_table = 'r4_code'
        unique_together = ('r_1_code', 'r_2_code', 'r_3_code', 'r_4_code')

    def _do_insert(self, manager, using, fields, update_pk, raw):
        fields = [
            f for f in fields if f.attname not in ['code_r4','key_r4_simple']
        ]
        return super()._do_insert(manager, using, fields, update_pk, raw)
    
    def _do_update(self, base_qs, using, pk_val, values, update_fields, forced_update):
        values = [
            value for value in values if value[0].attname not in ['code_r4','key_r4_simple']
        ]
        return super()._do_update(base_qs, using, pk_val, values, update_fields, forced_update)

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login
from .models import Question,R1Code,R2Code,R3Code,R4Code,Choice
from django.template import loader
from django.urls import reverse

def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {"latest_question_list": latest_question_list}
    return render(request, "polls/index.html", context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", {"question": question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

#def vote(request, question_id):
#    return HttpResponse("You're voting on question %s." % question_id)

def r1_codes(request):
    r1_code_list =  R1Code.objects.all().order_by('r_1_code')
    context = {"R1_kod_listesi": r1_code_list}
    return render(request, "polls/r1_codes.html", context)

def r2_codes(request):
    r2_code_list =  R2Code.objects.all().order_by('r_1_code','r_2_code')
    context = {"R2_kod_listesi": r2_code_list}
    return render(request, "polls/r2_codes.html", context) 

def r3_codes(request):
    r3_code_list =  R3Code.objects.all().order_by('r_1_code','r_2_code','r_3_code')
    context = {"R3_kod_listesi": r3_code_list}
    return render(request, "polls/r3_codes.html", context) 

def r4_codes(request):
    r4_code_list =  R4Code.objects.all().order_by('r_1_code','r_2_code','r_3_code','r_4_code')
    context = {"R4_kod_listesi": r4_code_list}
    return render(request, "polls/r4_codes.html", context) 

def r1_codes_detail(request, r_1_code):
    r1_code = get_object_or_404(R1Code, pk=r_1_code)
    r1_code_list = R1Code.objects.filter(r_1_code=r_1_code).order_by('r_1_code')
    context = {"R1_kod": r1_code, "R1_kod_listesi": r1_code_list}
    return render(request, "polls/r1_codes_detail.html", context)

def r2_codes_detail(request, r_1_code, r_2_code):
    r2_code = get_object_or_404(R2Code, r_1_code=r_1_code, r_2_code=r_2_code)
    r2_code_list = R2Code.objects.filter(r_1_code=r_1_code ,r_2_code = r_2_code).order_by('r_1_code','r_2_code')
    context = {"R1_kod": r_1_code, "R2_kod" : r2_code, "R2_kod_listesi": r2_code_list}
    return render(request, "polls/r2_codes_detail.html", context)

def r3_codes_detail(request, r_1_code, r_2_code, r_3_code):
    r3_code = get_object_or_404(R3Code, r_1_code=r_1_code, r_2_code=r_2_code, r_3_code=r_3_code)
    r3_code_list = R3Code.objects.filter(r_1_code=r_1_code ,r_2_code = r_2_code, r_3_code= r_3_code).order_by('r_1_code','r_2_code','r_3_code')
    context = {"R1_kod": r_1_code, "R2_kod" : r_2_code, "R3_kod": r3_code, "R3_kod_listesi": r3_code_list}
    return render(request, "polls/r3_codes_detail.html", context)

def r4_codes_detail(request, r_1_code, r_2_code, r_3_code, r_4_code):
    r4_code = get_object_or_404(R4Code, r_1_code=r_1_code, r_2_code=r_2_code, r_3_code=r_3_code, r_4_code=r_4_code)
    r4_code_list = R4Code.objects.filter(r_1_code=r_1_code ,r_2_code = r_2_code, r_3_code= r_3_code, r_4_code= r_4_code).order_by('r_1_code','r_2_code','r_3_code', 'r_4_code')
    context = {"R1_kod": r_1_code, "R2_kod" : r_2_code, "R3_kod": r_3_code, "R4_kod": r4_code, "R4_kod_listesi": r4_code_list}
    return render(request, "polls/r4_codes_detail.html", context)

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})

polls/templates/polls/detail.html
<form action="{% url 'polls:r1_codes/new/' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/r1_codes.html
<!DOCTYPE html>
<html>
  <head>
    <title>R1 Codes</title>
  </head>
  <body>
    <h1>List of R1 Codes</h1>
    <ul>                          
      {% for r1_code in R1_kod_listesi %}
        <li>
          <strong>R1 Code:<a href="{% url 'polls:r1_codes_detail' r1_code.r_1_code %}">{{ r1_code.r_1_code }}</a><br>
          <strong>Kod Açıklaması:</strong> {{ r1_code.r_1_desc_tr }}<br>
        </li><br>
      {% empty %}
        <li>No R1 codes found.</li>
      {% endfor %}
    </ul>
  </body>
</html>

polls/templates/polls/r1_codes_detail.html
<!DOCTYPE html>
<html>
  <head>
    <title>R1 KOD LİSTESİ</title>
  </head>
  <body>
<!-- This is a heading for the page -->
<h1>R1 KOD LİSTESİ</h1>
{% if R1_kod_listesi %}
<!-- This is an unordered list with two items showing R1 code and description-->
<ul>                                                                                                                                                    
  <li><strong>R1 Kodu:</strong> {{ R1_kod.r_1_code }}</li>
  <li><strong>Açıklama TR:</strong> {{ R1_kod.r_1_desc_tr }}</li>
  <li><strong>Açıklama EN:</strong>{{ R1_kod.r_1_desc_en }}</li><br>
</ul>

<!-- If there are no R2 codes found, display the following message -->
{% else %}
  <p>R1 Kod bulunamadı.</p>
{% endif %}


<h2><a href="{% url 'polls:r1_codes' %}">{{ 'GERİ' }}</a></h2>
  </body>
</html>

polls/templates/polls/r2_codes.html
<!DOCTYPE html>
<html>
  <head>
    <title>R2 KOD LİSTESİ</title>
  </head>
  <body>
    <h1>R2 KOD LİSTESİ</h1>
    <ul>
      {% for r2_code in R2_kod_listesi %}
        <li>
          <strong>R1 Kod:</strong> {{ r2_code.r_1_code }}<br>
          <strong>R2 Kod:</strong><a href="{% url 'polls:r2_codes_detail' r2_code.r_1_code r2_code.r_2_code %}">{{ r2_code.r_2_code }}</a><br>
          <strong>Kod Açıklaması TR:</strong> {{ r2_code.r_2_desc_tr }}<br>
          <strong>Kod Açıklaması EN:</strong> {{ r2_code.r_2_desc_en }}<br>
        </li><br>
      {% empty %}
        <li>R2 Kod bulunamadı.</li>
      {% endfor %}
    </ul>
  </body>
</html>

polls/templates/polls/r2_codes_detail.html
<!DOCTYPE html>
<html>
  <head>
    <title>R2 KOD LİSTESİ</title>
  </head>
  <body>
<!-- This is a heading for the page -->
<h1>R2 KOD LİSTESİ</h1>
{% if R2_kod_listesi %}
<!-- This is an unordered list with two items showing R1 code and description-->
<ul>
  <li><strong>R1 Kod:</strong> {{ R2_kod.r_1_code }}</li>
  <li><strong>R2 Kod:</strong> {{ R2_kod.r_2_code }}</li>
  <li><strong>Açıklama TR:</strong> {{ R2_kod.r_2_desc_tr }}</li>
  <li><strong>Açıklama EN:</strong> {{ R2_kod.r_2_desc_en }}</li>
</ul>

<!-- If there are no R2 codes found, display the following message -->
{% else %}
  <p>No R2 codes found.</p>
{% endif %}
  <h2><a href="{% url 'polls:r2_codes' %}">{{ 'GERİ' }}</a></h2>
  </body>
</html>

polls/templates/polls/r3_codes.html
<!DOCTYPE html>
<html>
  <head>
    <title>R3 KOD LİSTESİ</title>
  </head>
  <body>
    <h1>R3 KOD LİSTESİ</h1>
    <ul>
      {% for r3_code in R3_kod_listesi %}
        <li>
          <strong>R1 Kod:</strong> {{ r3_code.r_1_code }}<br>
          <strong>R2 Kod:</strong> {{ r3_code.r_2_code }}<br>
          <strong>R3 Kod:</strong> <a href="{% url 'polls:r3_codes_detail' r3_code.r_1_code r3_code.r_2_code r3_code.r_3_code %}">{{ r3_code.r_3_code }}</a> <br>          
          <strong>Kod Açıklaması TR:</strong> {{ r3_code.r_3_desc_tr }}<br>          
          <strong>Kod Açıklaması EN:</strong> {{ r3_code.r_3_desc_en }}<br>           
        </li>
      {% empty %}
        <li>R3 Kod bulunamadı.</li>
      {% endfor %}
    </ul>
  </body>
</html>

polls/templates/polls/r3_codes_detail.html
<!DOCTYPE html>
<html>
  <head>
    <title>R3 KOD LİSTESİ</title>
  </head>
  <body>
<!-- This is a heading for the page -->
<h1>R3 KOD DETAYI</h1>
{% if R3_kod_listesi %}
<!-- This is an unordered list with two items showing R1 code and description-->
<ul>
  <li><strong>R1 Kodu:</strong> {{ R3_kod.r_1_code }}</li>
  <li><strong>R2 Kodu:</strong> {{ R3_kod.r_2_code }}</li>
  <li><strong>R3 Kodu:</strong> {{ R3_kod.r_3_code }}</li>
  <li><strong>Açıklama TR:</strong> {{ R3_kod.r_3_desc_tr }}</li>
  <li><strong>Açıklama EN:</strong> {{ R3_kod.r_3_desc_en }}</li>
</ul>

<!-- If there are no R2 codes found, display the following message -->
{% else %}
  <p>R3 Kod bulunamadı.</p>
{% endif %}
  <h2><a href="{% url 'polls:r3_codes' %}">{{ 'GERİ' }}</a></h2>
  </body>
</html>

polls/templates/polls/r4_codes.html
<!DOCTYPE html>
<html>
  <head>
    <title>R4 KOD LİSTESİ</title>
  </head>
  <body>
    <h1>R4 KOD LİSTESİ</h1>
    <ul>
      {% for r4_code in R4_kod_listesi %}
        <li>
          <strong>R1 Kod:</strong> {{ r4_code.r_1_code }}<br>
          <strong>R2 Kod:</strong> {{ r4_code.r_2_code }}<br>
          <strong>R3 Kod:</strong> {{ r4_code.r_3_code }}<br>    
          <strong>R4 Kod:</strong> <a href="{% url 'polls:r4_codes_detail' r4_code.r_1_code r4_code.r_2_code r4_code.r_3_code r4_code.r_4_code %}">{{ r4_code.r_4_code }}</a><br>  
          <strong>Kod Açıklaması TR:</strong> {{ r4_code.r_4_desc_tr }}<br> 
          <strong>Kod Açıklaması EN:</strong> {{ r4_code.r_4_desc_en }}<br>     
        </li><br>
      {% empty %}
        <li>R4 Kod bulunamadı.</li>
      {% endfor %}
    </ul>
  </body>
</html>

polls/templates/polls/r4_codes_detail.html
<!DOCTYPE html>
<html>
  <head>
    <title>R4 KOD LİSTESİ</title>
  </head>
  <body>
<!-- This is a heading for the page -->
<h1>R4 KOD DETAYI</h1>
{% if R4_kod_listesi %}
<!-- This is an unordered list with two items showing R1 code and description-->
<ul>
  <li><strong>R1 Kod:</strong> {{ R4_kod.r_1_code }}</li>          
  <li><strong>R2 Kod:</strong> {{ R4_kod.r_2_code }}</li>          
  <li><strong>R3 Kod:</strong> {{ R4_kod.r_3_code }}</li>          
  <li><strong>R4 Kod:</strong> {{ R4_kod.r_4_code }}</li>          
  <li><strong>Açıklama TR:</strong> {{ R4_kod.r_4_desc_tr }}</li>          
  <li><strong>Açıklama EN:</strong> {{ R4_kod.r_4_desc_en }}</li>          
</ul><br>

<!-- If there are no R2 codes found, display the following message -->
{% else %}
  <p>R4 Kod bulunamadı.</p>
{% endif %}
  <h2 h2><a href="{% url 'polls:r4_codes' %}">{{ 'GERİ' }}</a></h2>
  </body>
</html>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>